#ifndef VOLLEYBALLGAME_APPLICATIONSTATUS_H
#define VOLLEYBALLGAME_APPLICATIONSTATUS_H

enum class ApplicationStatus {
    MAIN_MENU,
    GAME,
    PAUSE,
    EXIT,
};

#endif // VOLLEYBALLGAME_APPLICATIONSTATUS_H
