#ifndef VOLLEYBALLGAME_SRC_TEXTURES_H
#define VOLLEYBALLGAME_SRC_TEXTURES_H

enum class Textures {
    BACKGROUND_MAIN_MENU,
    BACKGROUND_GAME,
    BALL,
    BUTTON,
};

#endif //VOLLEYBALLGAME_SRC_TEXTURES_H
